# Version: 7
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - service.yaml
  - statefulset.yaml

configMapGenerator:
  - name: podverse-app-db-init-scripts
    files:
      - 0001_create_app_db_users.sh=source/bootstrap/0001_create_app_db_users.sh
  - name: podverse-management-init-scripts
    files:
      - 0002_create_management_db_users.sh=source/bootstrap/0002_create_management_db_users.sh
  - name: podverse-db-init-scripts
    files:
      - 0003_linear_baseline.sql=source/bootstrap/0003_linear_baseline.sql
      - 0004_seed_linear_migration_history.sql=source/bootstrap/0004_seed_linear_migration_history.sql

generatorOptions:
  disableNameSuffixHash: true
