---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-parser-live
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker-parser-live
  template:
    metadata:
      labels:
        app: worker-parser-live
      annotations:
        backup.velero.io/backup-volumes-excludes: "logs-volume"
    spec:
      containers:
        - name: worker
          image: ghcr.io/podverse/podverse/workers
          command:
            - node
            - apps/workers/dist/index.js
            - mqRSSRunParser
            - -q
            - rss-live
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - ALL
          resources:
            requests:
              cpu: "50m"
              memory: "32Mi"
            limits:
              cpu: "1000m"
              memory: "2Gi"
          livenessProbe:
            exec:
              command:
                - sh
                - -c
                - pidof node || exit 1
            initialDelaySeconds: 30
            periodSeconds: 20
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            exec:
              command:
                - sh
                - -c
                - pidof node || exit 1
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 3
          envFrom:
            - configMapRef:
                name: podverse-workers-config
            - secretRef:
                name: podverse-db-opaque
            - secretRef:
                name: podverse-mq-opaque
            - secretRef:
                name: podverse-api.podcastindex.org-opaque
            - secretRef:
                name: podverse-workers-add-by-rss-opaque
            - secretRef:
                name: podverse-workers-webpush-opaque
              optional: true
          volumeMounts:
            - name: logs-volume
              mountPath: /logs
            - name: logs-volume
              mountPath: /opt/logs
            - name: firebase-key
              mountPath: /var/secrets/firebase
              readOnly: true
      volumes:
        - name: logs-volume
          emptyDir: {}
        - name: firebase-key
          secret:
            secretName: podverse-workers-firebase-opaque
            optional: true
