# Version: 3
apiVersion: batch/v1
kind: Job
metadata:
  name: podverse-mq-provisioner
  labels:
    component: provisioner
  annotations:
    argocd.argoproj.io/hook: PostSync
spec:
  template:
    metadata:
      labels:
        component: provisioner
      annotations:
        backup.velero.io/backup-volumes-excludes: "scratch-data"
    spec:
      restartPolicy: OnFailure
      containers:
        - name: provisioner
          image: apache/activemq-artemis:2.37.0
          command: ["/bin/bash", "/scripts/provision-queues.sh"]
          envFrom:
            - secretRef:
                name: podverse-mq-opaque
          volumeMounts:
            - name: scripts
              mountPath: /scripts
            - name: scratch-data
              mountPath: /var/lib/artemis-instance
      volumes:
        - name: scripts
          configMap:
            name: podverse-mq-scripts
            defaultMode: 0755
        - name: scratch-data
          emptyDir: {}
