#!/bin/bash
set -e

# Ensure required env vars exist
: "${POSTGRES_MANAGEMENT_DB:?Missing POSTGRES_MANAGEMENT_DB}"
: "${POSTGRES_MANAGEMENT_USER:?Missing POSTGRES_MANAGEMENT_USER}"
: "${POSTGRES_MANAGEMENT_READ_USER:?Missing POSTGRES_MANAGEMENT_READ_USER}"
: "${POSTGRES_MANAGEMENT_READ_PASSWORD:?Missing POSTGRES_MANAGEMENT_READ_PASSWORD}"
: "${POSTGRES_MANAGEMENT_READ_WRITE_USER:?Missing POSTGRES_MANAGEMENT_READ_WRITE_USER}"
: "${POSTGRES_MANAGEMENT_READ_WRITE_PASSWORD:?Missing POSTGRES_MANAGEMENT_READ_WRITE_PASSWORD}"

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_MANAGEMENT_USER" --dbname "$POSTGRES_MANAGEMENT_DB" <<SQL
DO \$\$
BEGIN
    IF NOT EXISTS (SELECT FROM pg_catalog.pg_roles WHERE rolname = '${POSTGRES_MANAGEMENT_READ_USER}') THEN
        EXECUTE format('CREATE USER %I WITH PASSWORD %L', '${POSTGRES_MANAGEMENT_READ_USER}', '${POSTGRES_MANAGEMENT_READ_PASSWORD}');
    END IF;
END
\$\$;

DO \$\$
BEGIN
    IF NOT EXISTS (SELECT FROM pg_catalog.pg_roles WHERE rolname = '${POSTGRES_MANAGEMENT_READ_WRITE_USER}') THEN
        EXECUTE format('CREATE USER %I WITH PASSWORD %L', '${POSTGRES_MANAGEMENT_READ_WRITE_USER}', '${POSTGRES_MANAGEMENT_READ_WRITE_PASSWORD}');
    END IF;
END
\$\$;

-- Always sync passwords from env so DB stays aligned with local_env_setup (management-db.env)
DO \$\$
BEGIN
    EXECUTE format('ALTER USER %I WITH PASSWORD %L', '${POSTGRES_MANAGEMENT_READ_USER}', '${POSTGRES_MANAGEMENT_READ_PASSWORD}');
    EXECUTE format('ALTER USER %I WITH PASSWORD %L', '${POSTGRES_MANAGEMENT_READ_WRITE_USER}', '${POSTGRES_MANAGEMENT_READ_WRITE_PASSWORD}');
END
\$\$;

GRANT CONNECT ON DATABASE ${POSTGRES_MANAGEMENT_DB} TO ${POSTGRES_MANAGEMENT_READ_USER}, ${POSTGRES_MANAGEMENT_READ_WRITE_USER};
GRANT USAGE ON SCHEMA public TO ${POSTGRES_MANAGEMENT_READ_USER}, ${POSTGRES_MANAGEMENT_READ_WRITE_USER};

GRANT SELECT ON ALL TABLES IN SCHEMA public TO ${POSTGRES_MANAGEMENT_READ_USER};
GRANT SELECT ON ALL SEQUENCES IN SCHEMA public TO ${POSTGRES_MANAGEMENT_READ_USER};

GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO ${POSTGRES_MANAGEMENT_READ_WRITE_USER};
GRANT SELECT, USAGE, UPDATE ON ALL SEQUENCES IN SCHEMA public TO ${POSTGRES_MANAGEMENT_READ_WRITE_USER};

ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT ON TABLES TO ${POSTGRES_MANAGEMENT_READ_USER};
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT ON SEQUENCES TO ${POSTGRES_MANAGEMENT_READ_USER};
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO ${POSTGRES_MANAGEMENT_READ_WRITE_USER};
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT, USAGE, UPDATE ON SEQUENCES TO ${POSTGRES_MANAGEMENT_READ_WRITE_USER};
SQL
