CREATE TABLE public.account_pending_following_channel (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id integer NOT NULL,
    podcast_index_id integer,
    feed_url public.varchar_url NOT NULL,
    created_at public.server_time_with_default NOT NULL
);

ALTER TABLE ONLY public.account_pending_following_channel
    ADD CONSTRAINT account_pending_following_channel_account_id_feed_url_key UNIQUE (account_id, feed_url);

CREATE INDEX idx_account_pending_following_channel_account_id
    ON public.account_pending_following_channel USING btree (account_id);

CREATE INDEX idx_account_pending_following_channel_podcast_index_id
    ON public.account_pending_following_channel USING btree (podcast_index_id);

ALTER TABLE ONLY public.account_pending_following_channel
    ADD CONSTRAINT account_pending_following_channel_account_id_fkey FOREIGN KEY (account_id) REFERENCES public.account(id) ON DELETE CASCADE;

GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE public.account_pending_following_channel TO podverse_app_read_write;
GRANT SELECT ON TABLE public.account_pending_following_channel TO podverse_app_read;
