CREATE TYPE public.notification_category_options AS ENUM (
    'new-content',
    'livestream',
    'membership-expiry',
    'product-update',
    'maintenance',
    'terms-of-service',
    'general'
);

ALTER TABLE ONLY public.account
    ADD COLUMN notifications_last_seen_at timestamp with time zone;

CREATE TABLE public.account_notification (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id integer NOT NULL,
    category public.notification_category_options NOT NULL,
    title public.varchar_normal NOT NULL,
    body text,
    link_path public.varchar_normal,
    payload jsonb,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    expires_at timestamp with time zone DEFAULT (now() + '1 mon'::interval) NOT NULL
);

ALTER TABLE ONLY public.account_notification
    ADD CONSTRAINT account_notification_account_id_fkey FOREIGN KEY (account_id) REFERENCES public.account(id) ON DELETE CASCADE;

CREATE INDEX idx_account_notification_account_id_created_at
    ON public.account_notification USING btree (account_id, created_at DESC);

CREATE INDEX idx_account_notification_expires_at
    ON public.account_notification USING btree (expires_at);

CREATE TABLE public.account_notification_preference (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id integer NOT NULL,
    category public.notification_category_options NOT NULL,
    in_app_enabled boolean DEFAULT true NOT NULL,
    push_enabled boolean DEFAULT false NOT NULL
);

ALTER TABLE ONLY public.account_notification_preference
    ADD CONSTRAINT account_notification_preference_account_id_category_key UNIQUE (account_id, category);

ALTER TABLE ONLY public.account_notification_preference
    ADD CONSTRAINT account_notification_preference_account_id_fkey FOREIGN KEY (account_id) REFERENCES public.account(id) ON DELETE CASCADE;

CREATE INDEX idx_account_notification_preference_account_id
    ON public.account_notification_preference USING btree (account_id);

CREATE TABLE public.scheduled_job (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_type public.varchar_normal NOT NULL,
    dedupe_key public.varchar_normal NOT NULL,
    run_after timestamp with time zone NOT NULL,
    status public.varchar_short DEFAULT 'pending'::character varying NOT NULL,
    attempts integer DEFAULT 0 NOT NULL,
    max_attempts integer DEFAULT 5 NOT NULL,
    locked_at timestamp with time zone,
    locked_by public.varchar_short,
    payload jsonb DEFAULT '{}'::jsonb NOT NULL,
    last_error text,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT scheduled_job_attempts_nonnegative CHECK ((attempts >= 0)),
    CONSTRAINT scheduled_job_max_attempts_positive CHECK ((max_attempts > 0)),
    CONSTRAINT scheduled_job_status_check CHECK (((status)::text = ANY ((ARRAY['pending'::character varying, 'running'::character varying, 'completed'::character varying, 'cancelled'::character varying, 'failed'::character varying])::text[])))
);

ALTER TABLE ONLY public.scheduled_job
    ADD CONSTRAINT scheduled_job_dedupe_key_key UNIQUE (dedupe_key);

CREATE INDEX idx_scheduled_job_status_run_after
    ON public.scheduled_job USING btree (status, run_after)
    WHERE ((status)::text = 'pending'::text);

GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE public.account_notification TO podverse_app_read_write;
GRANT SELECT ON TABLE public.account_notification TO podverse_app_read;

GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE public.account_notification_preference TO podverse_app_read_write;
GRANT SELECT ON TABLE public.account_notification_preference TO podverse_app_read;

GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE public.scheduled_job TO podverse_app_read_write;
GRANT SELECT ON TABLE public.scheduled_job TO podverse_app_read;
