CREATE TABLE public.admin_notification_campaign (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_text public.varchar_id NOT NULL,
    title public.varchar_normal NOT NULL,
    body text,
    link_path public.varchar_normal,
    category public.notification_category_options NOT NULL,
    audience jsonb NOT NULL DEFAULT '{"type":"all-valid-membership"}'::jsonb,
    send_push boolean DEFAULT false NOT NULL,
    status public.varchar_short DEFAULT 'draft'::character varying NOT NULL,
    scheduled_at timestamp with time zone,
    sent_at timestamp with time zone,
    cancelled_at timestamp with time zone,
    created_by_admin_id integer,
    scheduled_job_dedupe_key public.varchar_normal,
    last_error text,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT admin_notification_campaign_id_text_key UNIQUE (id_text),
    CONSTRAINT admin_notification_campaign_status_check CHECK (((status)::text = ANY ((ARRAY['draft'::character varying, 'scheduled'::character varying, 'sending'::character varying, 'sent'::character varying, 'cancelled'::character varying])::text[])))
);

CREATE INDEX idx_admin_notification_campaign_created_at
    ON public.admin_notification_campaign USING btree (created_at DESC);

CREATE INDEX idx_admin_notification_campaign_status_scheduled_at
    ON public.admin_notification_campaign USING btree (status, scheduled_at);

CREATE INDEX idx_admin_notification_campaign_category
    ON public.admin_notification_campaign USING btree (category);

GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE public.admin_notification_campaign TO podverse_app_read_write;
GRANT SELECT ON TABLE public.admin_notification_campaign TO podverse_app_read;
