-- Per-installation auto-download channel registration for silent-push wakeups.
--
-- The phone is the source of truth for which podcasts auto-download. This table only tells the
-- parser which FCM / UnifiedPush installations to wake when a channel publishes new items.
-- Rows are replaced wholesale per (account, installation_id) on each sync.

CREATE TABLE public.account_device_auto_download_channel (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id integer NOT NULL,
    installation_id character varying(36) NOT NULL,
    channel_id integer NOT NULL,
    created_at timestamp without time zone DEFAULT now() NOT NULL,
    updated_at timestamp without time zone DEFAULT now() NOT NULL
);

ALTER TABLE ONLY public.account_device_auto_download_channel
    ADD CONSTRAINT account_device_auto_download_channel_account_install_channel_key
    UNIQUE (account_id, installation_id, channel_id);

ALTER TABLE ONLY public.account_device_auto_download_channel
    ADD CONSTRAINT account_device_auto_download_channel_account_id_fkey
    FOREIGN KEY (account_id) REFERENCES public.account(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.account_device_auto_download_channel
    ADD CONSTRAINT account_device_auto_download_channel_channel_id_fkey
    FOREIGN KEY (channel_id) REFERENCES public.channel(id) ON DELETE CASCADE;

CREATE INDEX idx_account_device_auto_download_channel_channel
    ON public.account_device_auto_download_channel (channel_id);

CREATE INDEX idx_account_device_auto_download_channel_install
    ON public.account_device_auto_download_channel (account_id, installation_id);

CREATE TRIGGER set_updated_at_account_device_auto_download_channel
    BEFORE UPDATE ON public.account_device_auto_download_channel
    FOR EACH ROW EXECUTE FUNCTION public.set_updated_at_field();

GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE public.account_device_auto_download_channel
    TO podverse_app_read_write;
GRANT SELECT ON TABLE public.account_device_auto_download_channel TO podverse_app_read;
