-- Membership billing: processors, checkout channels, payments, and a grant ledger that membership
-- access is derived from.
--
-- The cache is `membership_expires_at`, recomputed from `billing_membership_grant` under a row
-- lock. Every existing expiry becomes a `migration_baseline` grant. Podverse never charges a
-- card; every paid period comes from a settled processor payment.
--
-- Processor store product ids are environment-specific and are never seeded here.

-- ---------------------------------------------------------------------------------------------
-- Processors and checkout channels
-- ---------------------------------------------------------------------------------------------

CREATE TABLE public.billing_processor (
    id character varying(32) PRIMARY KEY,
    display_name text NOT NULL,
    is_active boolean DEFAULT true NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);

-- One row per processor and platform. A disabled channel stops clients offering that processor
-- on that platform without an app release. An empty storefront allowlist means every storefront.
-- Storefronts are ISO 3166-1 alpha-2 codes in upper case; clients normalize the store's code
-- before sending it.
CREATE TABLE public.billing_checkout_channel (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    processor_id character varying(32) NOT NULL,
    platform text NOT NULL,
    storefront_allowlist text[] DEFAULT '{}'::text[] NOT NULL,
    enabled boolean DEFAULT false NOT NULL,
    min_client_version character varying(32),
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT billing_checkout_channel_platform_check
        CHECK ((platform = ANY (ARRAY['web'::text, 'ios'::text, 'android'::text, 'foss'::text]))),
    CONSTRAINT billing_checkout_channel_storefront_allowlist_check
        CHECK ((array_to_string(storefront_allowlist, ',') ~ '^([A-Z]{2}(,[A-Z]{2})*)?$')),
    CONSTRAINT billing_checkout_channel_min_client_version_check
        CHECK (((min_client_version IS NULL) OR ((min_client_version)::text ~ '^[0-9]+(\.[0-9]+)*$')))
);

ALTER TABLE ONLY public.billing_checkout_channel
    ADD CONSTRAINT billing_checkout_channel_processor_platform_key UNIQUE (processor_id, platform);

ALTER TABLE ONLY public.billing_checkout_channel
    ADD CONSTRAINT billing_checkout_channel_processor_id_fkey
    FOREIGN KEY (processor_id) REFERENCES public.billing_processor(id);

-- Maps a store product id (plus Google Play base plan id) or PayPal checkout product id to the
-- catalog product and cadence it sells.
CREATE TABLE public.billing_processor_product (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    processor_id character varying(32) NOT NULL,
    external_product_id character varying(255) NOT NULL,
    external_base_plan_id character varying(255),
    billing_product_id integer NOT NULL,
    billing_cadence text NOT NULL,
    is_active boolean DEFAULT true NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT billing_processor_product_billing_cadence_check
        CHECK ((billing_cadence = ANY (ARRAY['monthly'::text, 'annual'::text])))
);

ALTER TABLE ONLY public.billing_processor_product
    ADD CONSTRAINT billing_processor_product_external_key
    UNIQUE NULLS NOT DISTINCT (processor_id, external_product_id, external_base_plan_id);

ALTER TABLE ONLY public.billing_processor_product
    ADD CONSTRAINT billing_processor_product_processor_id_fkey
    FOREIGN KEY (processor_id) REFERENCES public.billing_processor(id);

ALTER TABLE ONLY public.billing_processor_product
    ADD CONSTRAINT billing_processor_product_billing_product_id_fkey
    FOREIGN KEY (billing_product_id) REFERENCES public.billing_product(id);

-- ---------------------------------------------------------------------------------------------
-- Payments and the grant ledger
-- ---------------------------------------------------------------------------------------------

-- One row per settled payment. A refund, chargeback, or store revocation marks the row revoked
-- instead of adding a second row. Amounts are in major units; processors that do not report a
-- price leave amount and currency null together.
CREATE TABLE public.billing_transaction (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id integer NOT NULL,
    processor_id character varying(32) NOT NULL,
    external_transaction_id text NOT NULL,
    amount numeric(19,4),
    currency_code character(3),
    settled_at timestamp with time zone NOT NULL,
    revoked_at timestamp with time zone,
    revocation_reason text,
    is_sandbox boolean DEFAULT false NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT billing_transaction_amount_check CHECK (((amount IS NULL) OR (amount >= (0)::numeric))),
    CONSTRAINT billing_transaction_amount_currency_check
        CHECK (((amount IS NULL) = (currency_code IS NULL))),
    CONSTRAINT billing_transaction_revocation_reason_check
        CHECK ((revocation_reason = ANY (ARRAY['refund'::text, 'chargeback'::text, 'store_revoke'::text]))),
    CONSTRAINT billing_transaction_revocation_check
        CHECK (((revoked_at IS NULL) = (revocation_reason IS NULL)))
);

ALTER TABLE ONLY public.billing_transaction
    ADD CONSTRAINT billing_transaction_processor_external_key
    UNIQUE (processor_id, external_transaction_id);

ALTER TABLE ONLY public.billing_transaction
    ADD CONSTRAINT billing_transaction_account_id_fkey
    FOREIGN KEY (account_id) REFERENCES public.account(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.billing_transaction
    ADD CONSTRAINT billing_transaction_processor_id_fkey
    FOREIGN KEY (processor_id) REFERENCES public.billing_processor(id);

CREATE INDEX idx_billing_transaction_account_id
    ON public.billing_transaction USING btree (account_id);

-- Every way of getting membership time writes a grant. Revoked grants stay as history and grant
-- no access. A payment or a claim token creates at most one grant, so replaying the same
-- processor event or claim cannot add time twice.
CREATE TABLE public.billing_membership_grant (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id integer NOT NULL,
    source text NOT NULL,
    starts_at timestamp with time zone NOT NULL,
    ends_at timestamp with time zone NOT NULL,
    revoked_at timestamp with time zone,
    billing_transaction_id integer,
    membership_claim_token_id uuid,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT billing_membership_grant_source_check
        CHECK ((source = ANY (ARRAY['one_time_purchase'::text, 'claim_token'::text, 'admin'::text, 'trial'::text, 'legacy_import'::text, 'migration_baseline'::text]))),
    CONSTRAINT billing_membership_grant_window_check CHECK ((ends_at >= starts_at)),
    CONSTRAINT billing_membership_grant_one_time_purchase_check
        CHECK (((source <> 'one_time_purchase'::text) OR (billing_transaction_id IS NOT NULL))),
    CONSTRAINT billing_membership_grant_claim_token_check
        CHECK (((source <> 'claim_token'::text) OR (membership_claim_token_id IS NOT NULL)))
);

ALTER TABLE ONLY public.billing_membership_grant
    ADD CONSTRAINT billing_membership_grant_billing_transaction_id_key
    UNIQUE (billing_transaction_id);

ALTER TABLE ONLY public.billing_membership_grant
    ADD CONSTRAINT billing_membership_grant_membership_claim_token_id_key
    UNIQUE (membership_claim_token_id);

ALTER TABLE ONLY public.billing_membership_grant
    ADD CONSTRAINT billing_membership_grant_account_id_fkey
    FOREIGN KEY (account_id) REFERENCES public.account(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.billing_membership_grant
    ADD CONSTRAINT billing_membership_grant_billing_transaction_id_fkey
    FOREIGN KEY (billing_transaction_id) REFERENCES public.billing_transaction(id);

ALTER TABLE ONLY public.billing_membership_grant
    ADD CONSTRAINT billing_membership_grant_membership_claim_token_id_fkey
    FOREIGN KEY (membership_claim_token_id) REFERENCES public.membership_claim_token(id);

CREATE INDEX idx_billing_membership_grant_account_id
    ON public.billing_membership_grant USING btree (account_id);

-- Inbox of raw processor notifications. A redelivered notification hits the unique key and is
-- not processed twice; failed rows are retried from here.
CREATE TABLE public.billing_webhook_event (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    processor_id character varying(32) NOT NULL,
    external_event_id text NOT NULL,
    schema_version character varying(32) NOT NULL,
    payload jsonb NOT NULL,
    status text DEFAULT 'pending'::text NOT NULL,
    attempts integer DEFAULT 0 NOT NULL,
    received_at timestamp with time zone DEFAULT now() NOT NULL,
    processed_at timestamp with time zone,
    process_error text,
    CONSTRAINT billing_webhook_event_status_check
        CHECK ((status = ANY (ARRAY['pending'::text, 'processed'::text, 'failed'::text]))),
    CONSTRAINT billing_webhook_event_attempts_check CHECK ((attempts >= 0))
);

ALTER TABLE ONLY public.billing_webhook_event
    ADD CONSTRAINT billing_webhook_event_processor_external_key
    UNIQUE (processor_id, external_event_id);

ALTER TABLE ONLY public.billing_webhook_event
    ADD CONSTRAINT billing_webhook_event_processor_id_fkey
    FOREIGN KEY (processor_id) REFERENCES public.billing_processor(id);

CREATE INDEX idx_billing_webhook_event_unprocessed
    ON public.billing_webhook_event USING btree (received_at)
    WHERE (status <> 'processed'::text);

-- ---------------------------------------------------------------------------------------------
-- Account billing reference and membership status cache
-- ---------------------------------------------------------------------------------------------

-- Opaque per-account id attached to purchases (Apple `appAccountToken`, Google
-- `obfuscatedExternalAccountId`, PayPal `custom_id`) so processor notifications resolve to the
-- account without exposing its id. The volatile default gives every existing row its own value.
ALTER TABLE ONLY public.account
    ADD COLUMN billing_customer_ref uuid DEFAULT gen_random_uuid() NOT NULL;

ALTER TABLE ONLY public.account
    ADD CONSTRAINT account_billing_customer_ref_key UNIQUE (billing_customer_ref);

ALTER TABLE ONLY public.account_membership_status
    DROP COLUMN auto_renew,
    DROP COLUMN auto_renew_mode,
    DROP COLUMN next_renewal_attempt_at,
    DROP COLUMN last_renewal_attempt_at,
    DROP COLUMN last_renewal_status,
    DROP COLUMN last_renewal_idempotency_key,
    DROP COLUMN renewal_retry_count,
    DROP COLUMN renewal_retry_backoff_until;

-- Stored expiry and account creation times are UTC wall-clock values. A baseline grant runs from
-- account creation to the stored expiry; an expiry earlier than creation becomes a zero-length
-- grant that still dates the lapse.
INSERT INTO public.billing_membership_grant (account_id, source, starts_at, ends_at)
SELECT
    status.account_id,
    'migration_baseline',
    LEAST(account.created_at, status.membership_expires_at) AT TIME ZONE 'UTC',
    status.membership_expires_at AT TIME ZONE 'UTC'
FROM public.account_membership_status AS status
JOIN public.account AS account ON account.id = status.account_id
WHERE status.membership_expires_at IS NOT NULL;

-- ---------------------------------------------------------------------------------------------
-- Unused tables
-- ---------------------------------------------------------------------------------------------

DROP TABLE public.account_paypal_order;
DROP TABLE public.account_google_play_purchase;
DROP TABLE public.account_app_store_purchase;
DROP TABLE public.billing_domain_event;

-- ---------------------------------------------------------------------------------------------
-- Seed data
-- ---------------------------------------------------------------------------------------------

INSERT INTO public.billing_processor (id, display_name, is_active, created_at, updated_at) VALUES
    ('paypal', 'PayPal', true, '2000-01-01 00:00:00+00', '2000-01-01 00:00:00+00'),
    ('apple', 'Apple App Store', true, '2000-01-01 00:00:00+00', '2000-01-01 00:00:00+00'),
    ('google_play', 'Google Play', true, '2000-01-01 00:00:00+00', '2000-01-01 00:00:00+00'),
    ('test', 'Test', true, '2000-01-01 00:00:00+00', '2000-01-01 00:00:00+00');

-- Store builds sell through their store. PayPal in the store builds is a link-out to web checkout
-- that starts disabled until an operator enables it per storefront. The F-Droid build ships
-- without store billing, so it offers only the PayPal link-out.
INSERT INTO public.billing_checkout_channel
    (processor_id, platform, enabled, created_at, updated_at)
VALUES
    ('paypal', 'web', true, '2000-01-01 00:00:00+00', '2000-01-01 00:00:00+00'),
    ('apple', 'ios', true, '2000-01-01 00:00:00+00', '2000-01-01 00:00:00+00'),
    ('google_play', 'android', true, '2000-01-01 00:00:00+00', '2000-01-01 00:00:00+00'),
    ('paypal', 'ios', false, '2000-01-01 00:00:00+00', '2000-01-01 00:00:00+00'),
    ('paypal', 'android', false, '2000-01-01 00:00:00+00', '2000-01-01 00:00:00+00'),
    ('paypal', 'foss', true, '2000-01-01 00:00:00+00', '2000-01-01 00:00:00+00');

-- ---------------------------------------------------------------------------------------------
-- Triggers and grants
-- ---------------------------------------------------------------------------------------------

CREATE TRIGGER set_updated_at_billing_processor
    BEFORE UPDATE ON public.billing_processor
    FOR EACH ROW EXECUTE FUNCTION public.set_updated_at_field();

CREATE TRIGGER set_updated_at_billing_checkout_channel
    BEFORE UPDATE ON public.billing_checkout_channel
    FOR EACH ROW EXECUTE FUNCTION public.set_updated_at_field();

CREATE TRIGGER set_updated_at_billing_processor_product
    BEFORE UPDATE ON public.billing_processor_product
    FOR EACH ROW EXECUTE FUNCTION public.set_updated_at_field();

GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE public.billing_processor TO podverse_app_read_write;
GRANT SELECT ON TABLE public.billing_processor TO podverse_app_read;

GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE public.billing_checkout_channel TO podverse_app_read_write;
GRANT SELECT ON TABLE public.billing_checkout_channel TO podverse_app_read;

GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE public.billing_processor_product TO podverse_app_read_write;
GRANT SELECT ON TABLE public.billing_processor_product TO podverse_app_read;

GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE public.billing_transaction TO podverse_app_read_write;
GRANT SELECT ON TABLE public.billing_transaction TO podverse_app_read;

GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE public.billing_membership_grant TO podverse_app_read_write;
GRANT SELECT ON TABLE public.billing_membership_grant TO podverse_app_read;

GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE public.billing_webhook_event TO podverse_app_read_write;
GRANT SELECT ON TABLE public.billing_webhook_event TO podverse_app_read;
