# ==========================================
# Alpha Environment
# ==========================================

include Makefile.alpha.envfiles
include Makefile.alpha.infra
include Makefile.alpha.apps
