apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: podverse-alpha-mq
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
spec:
  project: <argocd-project>
  source:
    repoURL: <gitops-repo-url>
    targetRevision: <gitops-branch>
    path: apps/podverse-alpha/mq
  destination:
    server: https://kubernetes.default.svc
    namespace: podverse-alpha
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
