# Shared extension configuration (podverse-extensions-config).
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

configMapGenerator:
  - name: podverse-extensions-config
    envs:
      - source/extensions.env
      - source/extension-sidecar-otel.env
      - source/extension-prometheus.env

generatorOptions:
  disableNameSuffixHash: true
