# Version: 4
# Filename: kustomization.yaml
# Description: Bundles resources and acts as the "Variable" manager for images.
# RedisInsight (podverse-keyvaldb-gui) is in infra/k8s/alpha/ops.

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - https://github.com/podverse/podverse//infra/k8s/base/keyvaldb?ref=X.Y.Z-staging.N
  # Note: We will uncomment the secret line below once you run the generation script
  # - secrets/podverse-keyvaldb-secret.enc.yaml

# 2. Namespace to apply to all resources (optional, but good practice)
namespace: podverse-alpha

labels:
  - pairs:
      app: podverse-keyvaldb
      environment: alpha
    # This ensures the labels are also applied to the selectors,
    # so the Service correctly finds the Pods.
    includeSelectors: true

# 3. Image Variables
# Change the 'newTag' here to update versions across all files.
images:
  - name: valkey/valkey
    newTag: "9.0.1"
