import type { DTOFeed } from '../feed/feed.js';
import type { DTOChannelAbout } from './channelAbout.js';
import type { DTOChannelCategory } from './channelCategory.js';
import type { DTOChannelChat } from './channelChat.js';
import type { DTOChannelDescription } from './channelDescription.js';
import type { DTOChannelFunding } from './channelFunding.js';
import type { DTOChannelImage } from './channelImage.js';
import type { DTOChannelInternalSettings } from './channelInternalSettings.js';
import type { DTOChannelLicense } from './channelLicense.js';
import type { DTOChannelLocation } from './channelLocation.js';
import type { DTOChannelMetaBoost } from './channelMetaBoost.js';
import type { DTOChannelPerson } from './channelPerson.js';
import type { DTOChannelPodroll } from './channelPodroll.js';
import type { DTOChannelPublisher } from './channelPublisher.js';
import type { DTOChannelRemoteItem } from './channelRemoteItem.js';
import type { DTOChannelSeason } from './channelSeason.js';
import type { DTOChannelSocialInteract } from './channelSocialInteract.js';
import type { DTOChannelTrailer } from './channelTrailer.js';
import type { DTOChannelTxt } from './channelTxt.js';
import type { DTOChannelValue } from './channelValue.js';

export interface DTOChannel {
  id: number;
  id_text: string;
  slug: string | null;
  feed_id: number;
  podcast_guid: string | null;
  title: string | null;
  sortable_title: string | null;
  medium_id: number;
  has_podcast_index_value: boolean;
  has_value_time_splits: boolean;
  feed?: DTOFeed;
  channel_about?: DTOChannelAbout;
  channel_categories?: DTOChannelCategory[];
  channel_chat?: DTOChannelChat;
  channel_description?: DTOChannelDescription;
  channel_fundings?: DTOChannelFunding[];
  channel_images?: DTOChannelImage[];
  channel_internal_settings?: DTOChannelInternalSettings;
  channel_license?: DTOChannelLicense;
  channel_location?: DTOChannelLocation;
  channel_meta_boost?: DTOChannelMetaBoost | null;
  channel_persons?: DTOChannelPerson[];
  channel_podroll?: DTOChannelPodroll;
  channel_publisher?: DTOChannelPublisher;
  channel_remote_items?: DTOChannelRemoteItem[];
  channel_seasons?: DTOChannelSeason[];
  channel_social_interacts?: DTOChannelSocialInteract[];
  channel_trailers?: DTOChannelTrailer[];
  channel_txts?: DTOChannelTxt[];
  channel_values?: DTOChannelValue[];
}
