# Version: 2
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - service.yaml
  - deployment.yaml

configMapGenerator:
  - name: podverse-api-config
    envs:
      - source/api.env

generatorOptions:
  disableNameSuffixHash: true
