import {
  FIFTEEN_MINUTES_MS,
  FIVE_MINUTES_MS,
  ONE_HOUR_MS,
  ONE_MINUTE_MS,
} from '../timeConstants.js';

export const DEDUPE_WINDOW_RSS_SLOW_MS = FIFTEEN_MINUTES_MS;
export const DEDUPE_WINDOW_RSS_NORMAL_MS = FIVE_MINUTES_MS;
export const DEDUPE_WINDOW_RSS_ON_DEMAND_MS = ONE_MINUTE_MS;
export const DEDUPE_WINDOW_ADD_BY_RSS_ON_DEMAND_MS = ONE_MINUTE_MS;
export const DEDUPE_WINDOW_ADD_BY_RSS_BACKGROUND_MS = FIVE_MINUTES_MS;
export const DEDUPE_WINDOW_OPML_IMPORT_MS = ONE_MINUTE_MS;
export const DEDUPE_WINDOW_IMAGE_SHRINK_HINTS_MS = ONE_HOUR_MS;
