networks:
  podverse_local_network:
    external: true

services:
  podverse_local_api:
    build:
      context: ../..
      dockerfile: infra/docker/local/api/Dockerfile
    image: podverse-api:latest
    container_name: podverse_local_api
    env_file:
      - ../../../config/local/api.env
    networks:
      podverse_local_network:
        aliases:
          - podverse_local_api
    ports:
      - 127.0.0.1:1234:1234
    logging:
      driver: "json-file"
      options:
        max-file: "1"
        max-size: "50m"
