plugins {
  id 'com.android.library'
  id 'expo-module-gradle-plugin'
}

group = 'expo.modules.podverseperfprobe'
version = '1.0.0'

ext.safeExtGet = { prop, fallback ->
  rootProject.ext.has(prop) ? rootProject.ext.get(prop) : fallback
}

android {
  namespace "expo.modules.podverseperfprobe"
  compileSdkVersion safeExtGet("compileSdkVersion", 36)
  defaultConfig {
    minSdkVersion safeExtGet("minSdkVersion", 24)
    targetSdkVersion safeExtGet("targetSdkVersion", 36)
    versionCode 1
    versionName "1.0.0"
  }
  lint {
    abortOnError false
  }
}
