networks:
  podverse_local_network:
    external: true

services:
  podverse_local_management_web:
    image: podverse-management-web:latest
    container_name: podverse_local_management_web
    depends_on:
      - podverse_local_management_web_runtime_config
    env_file:
      - ../../../config/local/management-web.env
    networks:
      - podverse_local_network
    ports:
      - 127.0.0.1:3100:3100
    logging:
      driver: "json-file"
      options:
        max-file: "1"
        max-size: "50m"
  podverse_local_management_web_runtime_config:
    image: podverse-management-web-runtime-config:latest
    container_name: podverse_local_management_web_runtime_config
    env_file:
      - ../../../config/local/management-web.env
    environment:
      PORT: "3101"
    networks:
      - podverse_local_network
    logging:
      driver: "json-file"
      options:
        max-file: "1"
        max-size: "50m"
