import type { IntegrationsWebConfig } from '@podverse/integrations-web/config';
import type { RemoteThemeDefinition } from '@podverse/ui';

export type WebRuntimeConfigEnvKey =
  | 'NEXT_PUBLIC_ACCOUNT_SIGNUP_MODE'
  | 'NEXT_PUBLIC_API_HOST'
  | 'NEXT_PUBLIC_API_PORT'
  | 'NEXT_PUBLIC_API_PREFIX'
  | 'NEXT_PUBLIC_API_PROTOCOL'
  | 'NEXT_PUBLIC_API_VERSION'
  | 'NEXT_PUBLIC_APP_VALUE_LIGHTNING_LNADDRESS_ADDRESS'
  | 'NEXT_PUBLIC_APP_VALUE_LIGHTNING_LNADDRESS_NAME'
  | 'NEXT_PUBLIC_APP_VALUE_LIGHTNING_NODE_ADDRESS'
  | 'NEXT_PUBLIC_APP_VALUE_LIGHTNING_NODE_CUSTOM_KEY'
  | 'NEXT_PUBLIC_APP_VALUE_LIGHTNING_NODE_CUSTOM_VALUE'
  | 'NEXT_PUBLIC_APP_VALUE_LIGHTNING_NODE_NAME'
  | 'NEXT_PUBLIC_APP_VALUE_METABOOST_NODE'
  | 'NEXT_PUBLIC_APP_VALUE_METABOOST_STANDARD'
  | 'NEXT_PUBLIC_BRAND_DOMAIN'
  | 'NEXT_PUBLIC_BRAND_LOGO_DARK'
  | 'NEXT_PUBLIC_BRAND_LOGO_LIGHT'
  | 'NEXT_PUBLIC_BRAND_LOGO_SQUARE'
  | 'NEXT_PUBLIC_BRAND_LOGO_SQUARE_100X100'
  | 'NEXT_PUBLIC_BRAND_NAME'
  | 'NEXT_PUBLIC_CONTACT_EMAIL'
  | 'NEXT_PUBLIC_CUSTOM_THEMES_URL'
  | 'NEXT_PUBLIC_DEFAULT_THEME'
  | 'NEXT_PUBLIC_LEGAL_NAME'
  | 'NEXT_PUBLIC_BRAND_APPLE_TOUCH_ICON_URL'
  | 'NEXT_PUBLIC_BRAND_APP_ICON_192_URL'
  | 'NEXT_PUBLIC_BRAND_APP_ICON_512_URL'
  | 'NEXT_PUBLIC_BRAND_BACKGROUND_COLOR'
  | 'NEXT_PUBLIC_BRAND_FAVICON_ICO_URL'
  | 'NEXT_PUBLIC_BRAND_FAVICON_PNG_96_URL'
  | 'NEXT_PUBLIC_BRAND_FAVICON_SVG_URL'
  | 'NEXT_PUBLIC_BRAND_THEME_COLOR'
  | 'NEXT_PUBLIC_FEATURES_DEFAULT_LOCALE'
  | 'NEXT_PUBLIC_FEATURES_SUPPORTED_LOCALES'
  | 'NEXT_PUBLIC_COOKIE_CONSENT_BANNER_ENABLED'
  | 'NEXT_PUBLIC_IMAGE_PROXY_ENABLED'
  | 'NEXT_PUBLIC_NEXT_IMAGE_OPTIMIZATION_ENABLED'
  | 'NEXT_PUBLIC_POLLING_INTERVAL_MS'
  | 'NEXT_PUBLIC_PROXY_RESPONSE_CACHE_MAX_AGE_SECONDS'
  | 'NEXT_PUBLIC_PROXY_USER_AGENT'
  | 'NEXT_PUBLIC_SERVER_ENV'
  | 'NEXT_PUBLIC_SIDEBAR_GROUP_ORDER'
  | 'NEXT_PUBLIC_SOCIAL_ACTIVITY_PUB'
  | 'NEXT_PUBLIC_SOCIAL_DISCORD'
  | 'NEXT_PUBLIC_SOCIAL_GITHUB'
  | 'NEXT_PUBLIC_SOCIAL_MATRIX'
  | 'NEXT_PUBLIC_SOCIAL_X'
  | 'NEXT_PUBLIC_STATS_TRACK_EVENT_RETENTION_DAYS'
  | 'NEXT_PUBLIC_SSR_API_HOST'
  | 'NEXT_PUBLIC_SSR_API_PORT'
  | 'NEXT_PUBLIC_SSR_API_PROTOCOL'
  | 'NEXT_PUBLIC_SUPPORTED_THEMES'
  | 'NEXT_PUBLIC_TERMS_OF_SERVICE_VERSION'
  | 'NEXT_PUBLIC_WEBPUSH_VAPID_PUBLIC_KEY'
  | 'NEXT_PUBLIC_WEB_DOMAIN'
  | 'NEXT_PUBLIC_WEB_PROTOCOL';

export const webRuntimeConfigEnvKeys = {
  required: [
    'NEXT_PUBLIC_ACCOUNT_SIGNUP_MODE',
    'NEXT_PUBLIC_API_HOST',
    'NEXT_PUBLIC_API_PREFIX',
    'NEXT_PUBLIC_API_PROTOCOL',
    'NEXT_PUBLIC_API_VERSION',
    'NEXT_PUBLIC_DEFAULT_THEME',
    'NEXT_PUBLIC_FEATURES_DEFAULT_LOCALE',
    'NEXT_PUBLIC_FEATURES_SUPPORTED_LOCALES',
    'NEXT_PUBLIC_LEGAL_NAME',
    'NEXT_PUBLIC_SERVER_ENV',
    'NEXT_PUBLIC_SSR_API_HOST',
    'NEXT_PUBLIC_SSR_API_PROTOCOL',
    'NEXT_PUBLIC_SUPPORTED_THEMES',
    'NEXT_PUBLIC_TERMS_OF_SERVICE_VERSION',
    'NEXT_PUBLIC_WEB_DOMAIN',
    'NEXT_PUBLIC_WEB_PROTOCOL',
  ],
  optional: [
    'NEXT_PUBLIC_API_PORT',
    'NEXT_PUBLIC_APP_VALUE_LIGHTNING_LNADDRESS_ADDRESS',
    'NEXT_PUBLIC_APP_VALUE_LIGHTNING_LNADDRESS_NAME',
    'NEXT_PUBLIC_APP_VALUE_LIGHTNING_NODE_ADDRESS',
    'NEXT_PUBLIC_APP_VALUE_LIGHTNING_NODE_CUSTOM_KEY',
    'NEXT_PUBLIC_APP_VALUE_LIGHTNING_NODE_CUSTOM_VALUE',
    'NEXT_PUBLIC_APP_VALUE_LIGHTNING_NODE_NAME',
    'NEXT_PUBLIC_APP_VALUE_METABOOST_NODE',
    'NEXT_PUBLIC_APP_VALUE_METABOOST_STANDARD',
    'NEXT_PUBLIC_BRAND_DOMAIN',
    'NEXT_PUBLIC_BRAND_LOGO_DARK',
    'NEXT_PUBLIC_BRAND_LOGO_LIGHT',
    'NEXT_PUBLIC_BRAND_LOGO_SQUARE',
    'NEXT_PUBLIC_BRAND_LOGO_SQUARE_100X100',
    'NEXT_PUBLIC_BRAND_NAME',
    'NEXT_PUBLIC_BRAND_APPLE_TOUCH_ICON_URL',
    'NEXT_PUBLIC_BRAND_APP_ICON_192_URL',
    'NEXT_PUBLIC_BRAND_APP_ICON_512_URL',
    'NEXT_PUBLIC_BRAND_BACKGROUND_COLOR',
    'NEXT_PUBLIC_BRAND_FAVICON_ICO_URL',
    'NEXT_PUBLIC_BRAND_FAVICON_PNG_96_URL',
    'NEXT_PUBLIC_BRAND_FAVICON_SVG_URL',
    'NEXT_PUBLIC_BRAND_THEME_COLOR',
    'NEXT_PUBLIC_CONTACT_EMAIL',
    'NEXT_PUBLIC_CUSTOM_THEMES_URL',
    'NEXT_PUBLIC_COOKIE_CONSENT_BANNER_ENABLED',
    'NEXT_PUBLIC_IMAGE_PROXY_ENABLED',
    'NEXT_PUBLIC_NEXT_IMAGE_OPTIMIZATION_ENABLED',
    'NEXT_PUBLIC_POLLING_INTERVAL_MS',
    'NEXT_PUBLIC_PROXY_RESPONSE_CACHE_MAX_AGE_SECONDS',
    'NEXT_PUBLIC_PROXY_USER_AGENT',
    'NEXT_PUBLIC_SIDEBAR_GROUP_ORDER',
    'NEXT_PUBLIC_SOCIAL_ACTIVITY_PUB',
    'NEXT_PUBLIC_SOCIAL_DISCORD',
    'NEXT_PUBLIC_SOCIAL_GITHUB',
    'NEXT_PUBLIC_SOCIAL_MATRIX',
    'NEXT_PUBLIC_SOCIAL_X',
    'NEXT_PUBLIC_STATS_TRACK_EVENT_RETENTION_DAYS',
    'NEXT_PUBLIC_SSR_API_PORT',
    'NEXT_PUBLIC_WEBPUSH_VAPID_PUBLIC_KEY',
  ],
} as const;

export type WebRuntimeConfigValues = {
  [K in WebRuntimeConfigEnvKey]: string | undefined;
};

export type WebRuntimeConfig = {
  env: WebRuntimeConfigValues;
  integrations: IntegrationsWebConfig;
  customThemes?: RemoteThemeDefinition[];
};
