export type WebRuntimeConfigEnvKey =
  | 'NEXT_PUBLIC_ACCOUNT_SIGNUP_MODE'
  | 'NEXT_PUBLIC_API_HOST'
  | 'NEXT_PUBLIC_API_PORT'
  | 'NEXT_PUBLIC_API_PREFIX'
  | 'NEXT_PUBLIC_API_PROTOCOL'
  | 'NEXT_PUBLIC_API_VERSION'
  | 'NEXT_PUBLIC_APP_VALUE_LIGHTNING_LNADDRESS_ADDRESS'
  | 'NEXT_PUBLIC_APP_VALUE_LIGHTNING_LNADDRESS_NAME'
  | 'NEXT_PUBLIC_APP_VALUE_LIGHTNING_NODE_ADDRESS'
  | 'NEXT_PUBLIC_APP_VALUE_LIGHTNING_NODE_CUSTOM_KEY'
  | 'NEXT_PUBLIC_APP_VALUE_LIGHTNING_NODE_CUSTOM_VALUE'
  | 'NEXT_PUBLIC_APP_VALUE_LIGHTNING_NODE_NAME'
  | 'NEXT_PUBLIC_BRAND_NAME'
  | 'NEXT_PUBLIC_CONTACT_EMAIL'
  | 'NEXT_PUBLIC_DEFAULT_THEME'
  | 'NEXT_PUBLIC_FEATURES_DEFAULT_LOCALE'
  | 'NEXT_PUBLIC_FEATURES_SUPPORTED_LOCALES'
  | 'NEXT_PUBLIC_POLLING_INTERVAL_MS'
  | 'NEXT_PUBLIC_PROXY_USER_AGENT'
  | 'NEXT_PUBLIC_SERVER_ENV'
  | 'NEXT_PUBLIC_SOCIAL_ACTIVITY_PUB'
  | 'NEXT_PUBLIC_SOCIAL_DISCORD'
  | 'NEXT_PUBLIC_SOCIAL_GITHUB'
  | 'NEXT_PUBLIC_SOCIAL_MATRIX'
  | 'NEXT_PUBLIC_SOCIAL_X'
  | 'NEXT_PUBLIC_SSR_API_HOST'
  | 'NEXT_PUBLIC_SSR_API_PORT'
  | 'NEXT_PUBLIC_SSR_API_PROTOCOL'
  | 'NEXT_PUBLIC_SUPPORTED_THEMES'
  | 'NEXT_PUBLIC_WEBPUSH_VAPID_PUBLIC_KEY'
  | 'NEXT_PUBLIC_WEB_DOMAIN'
  | 'NEXT_PUBLIC_WEB_PROTOCOL';

export const webRuntimeConfigEnvKeys = {
  required: [
    'NEXT_PUBLIC_ACCOUNT_SIGNUP_MODE',
    'NEXT_PUBLIC_API_HOST',
    'NEXT_PUBLIC_API_PREFIX',
    'NEXT_PUBLIC_API_PROTOCOL',
    'NEXT_PUBLIC_API_VERSION',
    'NEXT_PUBLIC_DEFAULT_THEME',
    'NEXT_PUBLIC_FEATURES_DEFAULT_LOCALE',
    'NEXT_PUBLIC_FEATURES_SUPPORTED_LOCALES',
    'NEXT_PUBLIC_PROXY_USER_AGENT',
    'NEXT_PUBLIC_SERVER_ENV',
    'NEXT_PUBLIC_SSR_API_HOST',
    'NEXT_PUBLIC_SSR_API_PROTOCOL',
    'NEXT_PUBLIC_SUPPORTED_THEMES',
    'NEXT_PUBLIC_WEB_DOMAIN',
    'NEXT_PUBLIC_WEB_PROTOCOL',
  ],
  optional: [
    'NEXT_PUBLIC_API_PORT',
    'NEXT_PUBLIC_APP_VALUE_LIGHTNING_LNADDRESS_ADDRESS',
    'NEXT_PUBLIC_APP_VALUE_LIGHTNING_LNADDRESS_NAME',
    'NEXT_PUBLIC_APP_VALUE_LIGHTNING_NODE_ADDRESS',
    'NEXT_PUBLIC_APP_VALUE_LIGHTNING_NODE_CUSTOM_KEY',
    'NEXT_PUBLIC_APP_VALUE_LIGHTNING_NODE_CUSTOM_VALUE',
    'NEXT_PUBLIC_APP_VALUE_LIGHTNING_NODE_NAME',
    'NEXT_PUBLIC_BRAND_NAME',
    'NEXT_PUBLIC_CONTACT_EMAIL',
    'NEXT_PUBLIC_POLLING_INTERVAL_MS',
    'NEXT_PUBLIC_SOCIAL_ACTIVITY_PUB',
    'NEXT_PUBLIC_SOCIAL_DISCORD',
    'NEXT_PUBLIC_SOCIAL_GITHUB',
    'NEXT_PUBLIC_SOCIAL_MATRIX',
    'NEXT_PUBLIC_SOCIAL_X',
    'NEXT_PUBLIC_SSR_API_PORT',
    'NEXT_PUBLIC_WEBPUSH_VAPID_PUBLIC_KEY',
  ],
} as const;

export type WebRuntimeConfigValues = {
  [K in WebRuntimeConfigEnvKey]: string | undefined;
};

export type WebRuntimeConfig = {
  env: WebRuntimeConfigValues;
};
