export type ManagementWebRuntimeConfigEnvKey =
  | 'NEXT_PUBLIC_API_HOST'
  | 'NEXT_PUBLIC_API_PORT'
  | 'NEXT_PUBLIC_API_PREFIX'
  | 'NEXT_PUBLIC_API_PROTOCOL'
  | 'NEXT_PUBLIC_API_VERSION'
  | 'NEXT_PUBLIC_APPLE_TOUCH_ICON_URL'
  | 'NEXT_PUBLIC_BRAND_DOMAIN'
  | 'NEXT_PUBLIC_BRAND_NAME'
  | 'NEXT_PUBLIC_FAVICON_ICO_URL'
  | 'NEXT_PUBLIC_FAVICON_PNG_96_URL'
  | 'NEXT_PUBLIC_FAVICON_SVG_URL'
  | 'NEXT_PUBLIC_FEATURES_DEFAULT_LOCALE'
  | 'NEXT_PUBLIC_FEATURES_SUPPORTED_LOCALES'
  | 'NEXT_PUBLIC_PWA_BACKGROUND_COLOR'
  | 'NEXT_PUBLIC_PWA_ICON_192_URL'
  | 'NEXT_PUBLIC_PWA_ICON_512_URL'
  | 'NEXT_PUBLIC_PWA_THEME_COLOR'
  | 'NEXT_PUBLIC_SSR_API_HOST'
  | 'NEXT_PUBLIC_SSR_API_PORT'
  | 'NEXT_PUBLIC_SSR_API_PROTOCOL';

export const managementWebRuntimeConfigEnvKeys = {
  required: [
    'NEXT_PUBLIC_API_HOST',
    'NEXT_PUBLIC_API_PREFIX',
    'NEXT_PUBLIC_API_PROTOCOL',
    'NEXT_PUBLIC_API_VERSION',
    'NEXT_PUBLIC_FEATURES_DEFAULT_LOCALE',
    'NEXT_PUBLIC_FEATURES_SUPPORTED_LOCALES',
    'NEXT_PUBLIC_SSR_API_HOST',
    'NEXT_PUBLIC_SSR_API_PORT',
    'NEXT_PUBLIC_SSR_API_PROTOCOL',
  ],
  optional: [
    'NEXT_PUBLIC_API_PORT',
    'NEXT_PUBLIC_APPLE_TOUCH_ICON_URL',
    'NEXT_PUBLIC_BRAND_DOMAIN',
    'NEXT_PUBLIC_BRAND_NAME',
    'NEXT_PUBLIC_FAVICON_ICO_URL',
    'NEXT_PUBLIC_FAVICON_PNG_96_URL',
    'NEXT_PUBLIC_FAVICON_SVG_URL',
    'NEXT_PUBLIC_PWA_BACKGROUND_COLOR',
    'NEXT_PUBLIC_PWA_ICON_192_URL',
    'NEXT_PUBLIC_PWA_ICON_512_URL',
    'NEXT_PUBLIC_PWA_THEME_COLOR',
  ],
} as const;

export type ManagementWebRuntimeConfigValues = {
  [K in ManagementWebRuntimeConfigEnvKey]: string | undefined;
};

export type ManagementWebRuntimeConfig = {
  env: ManagementWebRuntimeConfigValues;
};
