apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - worker-billing-renewals.cronjob.yaml
  - worker-recent-feeds.cronjob.yaml
  - worker-archive-all.cronjob.yaml
  - worker-generate-reports.cronjob.yaml
  - worker-dead-feeds-merge.cronjob.yaml
  - worker-delete-outdated.cronjob.yaml
  - worker-image-shrink-backfill.cronjob.yaml
  - worker-image-shrink-orphan-cleanup.cronjob.yaml
  - worker-image-shrink-reset-shrunken-dry-run.cronjob.yaml
  - worker-image-shrink-reset-shrunken.cronjob.yaml
  - worker-image-shrink-source-prune.cronjob.yaml
