apiVersion: batch/v1
kind: CronJob
metadata:
  name: worker-image-shrink-orphan-cleanup
spec:
  schedule: "0 3 * * 0"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        metadata:
          annotations:
            backup.velero.io/backup-volumes-excludes: "logs-volume"
        spec:
          containers:
            - name: worker
              image: ghcr.io/podverse/podverse/workers
              command:
                - "node"
                - "apps/workers/dist/index.js"
                - "imageShrinkCleanupOrphans"
              securityContext:
                runAsUser: 1000
                runAsGroup: 1000
                runAsNonRoot: true
                readOnlyRootFilesystem: true
                allowPrivilegeEscalation: false
              resources:
                requests:
                  memory: "512Mi"
                  cpu: "100m"
                limits:
                  memory: "1Gi"
                  cpu: "500m"
              envFrom:
                - configMapRef:
                    name: podverse-workers-config
                - secretRef:
                    name: podverse-db-opaque
                - secretRef:
                    name: podverse-mq-opaque
                - secretRef:
                    name: podverse-workers-add-by-rss-opaque
                - secretRef:
                    name: podverse-workers-webpush-opaque
              volumeMounts:
                - name: logs-volume
                  mountPath: /logs
                - name: logs-volume
                  mountPath: /opt/logs
                - name: firebase-key
                  mountPath: /var/secrets/firebase
                  readOnly: true
          volumes:
            - name: logs-volume
              emptyDir: {}
            - name: firebase-key
              secret:
                secretName: podverse-workers-firebase-opaque
                optional: true
          restartPolicy: OnFailure
