#!/usr/bin/env bash
# Ops-only: mirrors StatefulSet bootstrap `0001_create_app_db_users.sh` + `0002_create_management_db_users.sh`
# over TCP with passwords (PGHOST/PGPASSWORD). Keep aligned when editing:
#   infra/k8s/base/db/source/bootstrap/0001_create_app_db_users.sh
#   infra/k8s/base/db/source/bootstrap/0002_create_management_db_users.sh
#
# Required env: podverse-db-opaque + podverse-management-db-opaque keys (same as bootstrap shells).

set -euo pipefail

export PGHOST="${DB_HOST:-podverse-db}"
export PGPORT="${DB_PORT:-5432}"

: "${DB_APP_OWNER_USER:?Missing DB_APP_OWNER_USER}"
: "${DB_APP_OWNER_PASSWORD:?Missing DB_APP_OWNER_PASSWORD}"
: "${DB_APP_NAME:?Missing DB_APP_NAME}"
: "${DB_APP_MIGRATOR_USER:?Missing DB_APP_MIGRATOR_USER}"
: "${DB_APP_MIGRATOR_PASSWORD:?Missing DB_APP_MIGRATOR_PASSWORD}"
: "${DB_APP_READ_WRITE_USER:?Missing DB_APP_READ_WRITE_USER}"
: "${DB_APP_READ_WRITE_PASSWORD:?Missing DB_APP_READ_WRITE_PASSWORD}"
: "${DB_APP_READ_USER:?Missing DB_APP_READ_USER}"
: "${DB_APP_READ_PASSWORD:?Missing DB_APP_READ_PASSWORD}"

: "${DB_MANAGEMENT_NAME:?Missing DB_MANAGEMENT_NAME}"
: "${DB_MANAGEMENT_OWNER_USER:?Missing DB_MANAGEMENT_OWNER_USER}"
: "${DB_MANAGEMENT_OWNER_PASSWORD:?Missing DB_MANAGEMENT_OWNER_PASSWORD}"
: "${DB_MANAGEMENT_MIGRATOR_USER:?Missing DB_MANAGEMENT_MIGRATOR_USER}"
: "${DB_MANAGEMENT_MIGRATOR_PASSWORD:?Missing DB_MANAGEMENT_MIGRATOR_PASSWORD}"
: "${DB_MANAGEMENT_READ_WRITE_USER:?Missing DB_MANAGEMENT_READ_WRITE_USER}"
: "${DB_MANAGEMENT_READ_WRITE_PASSWORD:?Missing DB_MANAGEMENT_READ_WRITE_PASSWORD}"
: "${DB_MANAGEMENT_READ_USER:?Missing DB_MANAGEMENT_READ_USER}"
: "${DB_MANAGEMENT_READ_PASSWORD:?Missing DB_MANAGEMENT_READ_PASSWORD}"

echo "rebootstrap-full-bootstrap: Phase A — app DB (${DB_APP_NAME}) same as 0001_create_app_db_users.sh"

export PGPASSWORD="${DB_APP_OWNER_PASSWORD}"
psql -v ON_ERROR_STOP=1 --username "${DB_APP_OWNER_USER}" --dbname "${DB_APP_NAME}" <<SQL
DO \$\$
BEGIN
    IF NOT EXISTS (SELECT FROM pg_catalog.pg_roles WHERE rolname = '${DB_APP_MIGRATOR_USER}') THEN
        EXECUTE format('CREATE USER %I WITH PASSWORD %L', '${DB_APP_MIGRATOR_USER}', '${DB_APP_MIGRATOR_PASSWORD}');
    END IF;
END
\$\$;

DO \$\$
BEGIN
    IF NOT EXISTS (SELECT FROM pg_catalog.pg_roles WHERE rolname = '${DB_APP_READ_WRITE_USER}') THEN
        EXECUTE format('CREATE USER %I WITH PASSWORD %L', '${DB_APP_READ_WRITE_USER}', '${DB_APP_READ_WRITE_PASSWORD}');
    END IF;
END
\$\$;

DO \$\$
BEGIN
    IF NOT EXISTS (SELECT FROM pg_catalog.pg_roles WHERE rolname = '${DB_APP_READ_USER}') THEN
        EXECUTE format('CREATE USER %I WITH PASSWORD %L', '${DB_APP_READ_USER}', '${DB_APP_READ_PASSWORD}');
    END IF;
END
\$\$;

DO \$\$
BEGIN
    EXECUTE format('ALTER USER %I WITH PASSWORD %L', '${DB_APP_MIGRATOR_USER}', '${DB_APP_MIGRATOR_PASSWORD}');
    EXECUTE format('ALTER USER %I WITH PASSWORD %L', '${DB_APP_READ_WRITE_USER}', '${DB_APP_READ_WRITE_PASSWORD}');
    EXECUTE format('ALTER USER %I WITH PASSWORD %L', '${DB_APP_READ_USER}', '${DB_APP_READ_PASSWORD}');
END
\$\$;

GRANT CONNECT ON DATABASE ${DB_APP_NAME} TO ${DB_APP_MIGRATOR_USER}, ${DB_APP_READ_WRITE_USER}, ${DB_APP_READ_USER};
GRANT USAGE, CREATE ON SCHEMA public TO ${DB_APP_MIGRATOR_USER};
GRANT USAGE ON SCHEMA public TO ${DB_APP_READ_WRITE_USER}, ${DB_APP_READ_USER};
SQL

export PGPASSWORD="${DB_APP_MIGRATOR_PASSWORD}"
psql -v ON_ERROR_STOP=1 --username "${DB_APP_MIGRATOR_USER}" --dbname "${DB_APP_NAME}" <<SQL
DO \$\$
BEGIN
    IF NOT has_schema_privilege('${DB_APP_READ_WRITE_USER}', 'public', 'USAGE') THEN
        EXECUTE format('GRANT USAGE ON SCHEMA public TO %I', '${DB_APP_READ_WRITE_USER}');
    END IF;

    IF NOT has_schema_privilege('${DB_APP_READ_USER}', 'public', 'USAGE') THEN
        EXECUTE format('GRANT USAGE ON SCHEMA public TO %I', '${DB_APP_READ_USER}');
    END IF;
END
\$\$;

GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO ${DB_APP_READ_WRITE_USER};
GRANT SELECT, USAGE, UPDATE ON ALL SEQUENCES IN SCHEMA public TO ${DB_APP_READ_WRITE_USER};

GRANT SELECT ON ALL TABLES IN SCHEMA public TO ${DB_APP_READ_USER};
GRANT SELECT ON ALL SEQUENCES IN SCHEMA public TO ${DB_APP_READ_USER};

ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO ${DB_APP_READ_WRITE_USER};
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT, USAGE, UPDATE ON SEQUENCES TO ${DB_APP_READ_WRITE_USER};
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT ON TABLES TO ${DB_APP_READ_USER};
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT ON SEQUENCES TO ${DB_APP_READ_USER};
SQL

echo "rebootstrap-full-bootstrap: Phase B — management roles + DB same as start of 0002_create_management_db_users.sh"

export PGPASSWORD="${DB_APP_OWNER_PASSWORD}"
psql -v ON_ERROR_STOP=1 --username "${DB_APP_OWNER_USER}" --dbname "${DB_APP_NAME}" <<SQL
DO \$\$
BEGIN
    IF NOT EXISTS (SELECT FROM pg_catalog.pg_roles WHERE rolname = '${DB_MANAGEMENT_OWNER_USER}') THEN
        EXECUTE format('CREATE USER %I WITH PASSWORD %L', '${DB_MANAGEMENT_OWNER_USER}', '${DB_MANAGEMENT_OWNER_PASSWORD}');
    ELSE
        EXECUTE format('ALTER USER %I WITH NOCREATEDB NOCREATEROLE PASSWORD %L', '${DB_MANAGEMENT_OWNER_USER}', '${DB_MANAGEMENT_OWNER_PASSWORD}');
    END IF;
END
\$\$;

DO \$\$
BEGIN
    IF NOT EXISTS (SELECT FROM pg_catalog.pg_roles WHERE rolname = '${DB_MANAGEMENT_MIGRATOR_USER}') THEN
        EXECUTE format('CREATE USER %I WITH PASSWORD %L', '${DB_MANAGEMENT_MIGRATOR_USER}', '${DB_MANAGEMENT_MIGRATOR_PASSWORD}');
    END IF;
END
\$\$;

DO \$\$
BEGIN
    IF NOT EXISTS (SELECT FROM pg_catalog.pg_roles WHERE rolname = '${DB_MANAGEMENT_READ_WRITE_USER}') THEN
        EXECUTE format('CREATE USER %I WITH PASSWORD %L', '${DB_MANAGEMENT_READ_WRITE_USER}', '${DB_MANAGEMENT_READ_WRITE_PASSWORD}');
    END IF;
END
\$\$;

DO \$\$
BEGIN
    IF NOT EXISTS (SELECT FROM pg_catalog.pg_roles WHERE rolname = '${DB_MANAGEMENT_READ_USER}') THEN
        EXECUTE format('CREATE USER %I WITH PASSWORD %L', '${DB_MANAGEMENT_READ_USER}', '${DB_MANAGEMENT_READ_PASSWORD}');
    END IF;
END
\$\$;
SQL

DB_EXISTS="$(psql -v ON_ERROR_STOP=1 -U "${DB_APP_OWNER_USER}" -d "${DB_APP_NAME}" -tAc "SELECT 1 FROM pg_database WHERE datname='${DB_MANAGEMENT_NAME}'")"
if [ "${DB_EXISTS}" != "1" ]; then
  psql -v ON_ERROR_STOP=1 -U "${DB_APP_OWNER_USER}" -d "${DB_APP_NAME}" -c "CREATE DATABASE ${DB_MANAGEMENT_NAME} OWNER ${DB_MANAGEMENT_OWNER_USER};"
fi

psql -v ON_ERROR_STOP=1 --username "${DB_APP_OWNER_USER}" --dbname "${DB_APP_NAME}" -c "ALTER USER \"${DB_MANAGEMENT_OWNER_USER}\" WITH PASSWORD '${DB_MANAGEMENT_OWNER_PASSWORD}';"
psql -v ON_ERROR_STOP=1 --username "${DB_APP_OWNER_USER}" --dbname "${DB_APP_NAME}" -c "ALTER USER \"${DB_MANAGEMENT_MIGRATOR_USER}\" WITH PASSWORD '${DB_MANAGEMENT_MIGRATOR_PASSWORD}';"
psql -v ON_ERROR_STOP=1 --username "${DB_APP_OWNER_USER}" --dbname "${DB_APP_NAME}" -c "ALTER USER \"${DB_MANAGEMENT_READ_WRITE_USER}\" WITH PASSWORD '${DB_MANAGEMENT_READ_WRITE_PASSWORD}';"
psql -v ON_ERROR_STOP=1 --username "${DB_APP_OWNER_USER}" --dbname "${DB_APP_NAME}" -c "ALTER USER \"${DB_MANAGEMENT_READ_USER}\" WITH PASSWORD '${DB_MANAGEMENT_READ_PASSWORD}';"
psql -v ON_ERROR_STOP=1 --username "${DB_APP_OWNER_USER}" --dbname "${DB_APP_NAME}" -c "ALTER DATABASE \"${DB_MANAGEMENT_NAME}\" OWNER TO \"${DB_MANAGEMENT_OWNER_USER}\";"

echo "rebootstrap-full-bootstrap: Phase C — management DB (${DB_MANAGEMENT_NAME}) grants same as end of 0002"

export PGPASSWORD="${DB_MANAGEMENT_OWNER_PASSWORD}"
psql -v ON_ERROR_STOP=1 --username "${DB_MANAGEMENT_OWNER_USER}" --dbname "${DB_MANAGEMENT_NAME}" <<SQL
GRANT CONNECT ON DATABASE ${DB_MANAGEMENT_NAME} TO ${DB_MANAGEMENT_MIGRATOR_USER}, ${DB_MANAGEMENT_READ_WRITE_USER}, ${DB_MANAGEMENT_READ_USER};
GRANT USAGE, CREATE ON SCHEMA public TO ${DB_MANAGEMENT_MIGRATOR_USER};
GRANT USAGE ON SCHEMA public TO ${DB_MANAGEMENT_READ_WRITE_USER}, ${DB_MANAGEMENT_READ_USER};
SQL

export PGPASSWORD="${DB_MANAGEMENT_MIGRATOR_PASSWORD}"
psql -v ON_ERROR_STOP=1 --username "${DB_MANAGEMENT_MIGRATOR_USER}" --dbname "${DB_MANAGEMENT_NAME}" <<SQL
DO \$\$
BEGIN
    IF NOT has_schema_privilege('${DB_MANAGEMENT_READ_WRITE_USER}', 'public', 'USAGE') THEN
        EXECUTE format('GRANT USAGE ON SCHEMA public TO %I', '${DB_MANAGEMENT_READ_WRITE_USER}');
    END IF;

    IF NOT has_schema_privilege('${DB_MANAGEMENT_READ_USER}', 'public', 'USAGE') THEN
        EXECUTE format('GRANT USAGE ON SCHEMA public TO %I', '${DB_MANAGEMENT_READ_USER}');
    END IF;
END
\$\$;

GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO ${DB_MANAGEMENT_READ_WRITE_USER};
GRANT SELECT, USAGE, UPDATE ON ALL SEQUENCES IN SCHEMA public TO ${DB_MANAGEMENT_READ_WRITE_USER};

GRANT SELECT ON ALL TABLES IN SCHEMA public TO ${DB_MANAGEMENT_READ_USER};
GRANT SELECT ON ALL SEQUENCES IN SCHEMA public TO ${DB_MANAGEMENT_READ_USER};

ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO ${DB_MANAGEMENT_READ_WRITE_USER};
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT, USAGE, UPDATE ON SEQUENCES TO ${DB_MANAGEMENT_READ_WRITE_USER};
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT ON TABLES TO ${DB_MANAGEMENT_READ_USER};
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT ON SEQUENCES TO ${DB_MANAGEMENT_READ_USER};
SQL

echo "rebootstrap-full-bootstrap: completed successfully."
