import { APP_ROUTES } from '@podverse/helpers';

export const ROUTES = {
  ...APP_ROUTES,
  ABOUT: '/about',
  ADD_BY_RSS_ADD: '/add-by-rss/add',
  ADD_BY_RSS_ALBUMS: '/add-by-rss/albums',
  ADD_BY_RSS_ARTISTS: '/add-by-rss/artists',
  ADD_BY_RSS_EPISODES: '/add-by-rss/episodes',
  ADD_BY_RSS_LIVESTREAMS: '/add-by-rss/livestreams',
  ADD_BY_RSS_PODCASTS: '/add-by-rss/podcasts',
  ADD_BY_RSS_TRACKS: '/add-by-rss/tracks',
  ALBUMS: '/albums',
  ARTISTS: '/artists',
  CHANNELS: '/channels',
  CHAPTER: '/chapter',
  CLIPS: '/clips',
  CHECKOUT: '/checkout',
  CONTACT: '/contact',
  DONATE: '/donate',
  EMBED: '/embed',
  EMBED_BUILDER: '/embed/builder',
  EPISODES: '/episodes',
  HISTORY: '/history',
  MOBILE_APP: '/mobile-app',
  MUSIC_LIVESTREAMS: '/music/livestreams',
  MY_CLIPS: '/my-clips',
  MY_PROFILE: '/my-profile',
  OFFICIAL_CLIP: '/official-clip',
  PLAYLISTS: '/playlists',
  PODCASTS: '/podcasts',
  PODCASTS_LIVESTREAMS: '/podcasts/livestreams',
  PODCAST_INDEX: '/podcast-index',
  PROFILES: '/profiles',
  QUEUES: '/queues',
  SEARCH: '/search',
  SIGN_UP: '/sign-up',
  TERMS: '/terms',
  TRACKS: '/tracks',
  VIDEOS: '/videos',
} as const;
