#!/bin/bash
set -e

# Ensure required env vars exist
: "${DB_APP_READ_USER:?Missing DB_APP_READ_USER}"
: "${DB_APP_READ_PASSWORD:?Missing DB_APP_READ_PASSWORD}"
: "${DB_APP_READ_WRITE_USER:?Missing DB_APP_READ_WRITE_USER}"
: "${DB_APP_READ_WRITE_PASSWORD:?Missing DB_APP_READ_WRITE_PASSWORD}"

psql -v ON_ERROR_STOP=1 --username "$DB_APP_ADMIN_USER" --dbname "$DB_APP_NAME" <<SQL
DO \$\$
BEGIN
    IF NOT EXISTS (SELECT FROM pg_catalog.pg_roles WHERE rolname = '${DB_APP_READ_USER}') THEN
        EXECUTE format('CREATE USER %I WITH PASSWORD %L', '${DB_APP_READ_USER}', '${DB_APP_READ_PASSWORD}');
    END IF;
END
\$\$;

DO \$\$
BEGIN
    IF NOT EXISTS (SELECT FROM pg_catalog.pg_roles WHERE rolname = '${DB_APP_READ_WRITE_USER}') THEN
        EXECUTE format('CREATE USER %I WITH PASSWORD %L', '${DB_APP_READ_WRITE_USER}', '${DB_APP_READ_WRITE_PASSWORD}');
    END IF;
END
\$\$;

-- Always sync passwords from env so DB stays aligned with local_env_setup (db.env)
DO \$\$
BEGIN
    EXECUTE format('ALTER USER %I WITH PASSWORD %L', '${DB_APP_READ_USER}', '${DB_APP_READ_PASSWORD}');
    EXECUTE format('ALTER USER %I WITH PASSWORD %L', '${DB_APP_READ_WRITE_USER}', '${DB_APP_READ_WRITE_PASSWORD}');
END
\$\$;

GRANT CONNECT ON DATABASE ${DB_APP_NAME} TO ${DB_APP_READ_USER}, ${DB_APP_READ_WRITE_USER};
GRANT USAGE ON SCHEMA public TO ${DB_APP_READ_USER}, ${DB_APP_READ_WRITE_USER};

GRANT SELECT ON ALL TABLES IN SCHEMA public TO ${DB_APP_READ_USER};
GRANT SELECT ON ALL SEQUENCES IN SCHEMA public TO ${DB_APP_READ_USER};

GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO ${DB_APP_READ_WRITE_USER};
GRANT SELECT, USAGE, UPDATE ON ALL SEQUENCES IN SCHEMA public TO ${DB_APP_READ_WRITE_USER};

ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT ON TABLES TO ${DB_APP_READ_USER};
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT ON SEQUENCES TO ${DB_APP_READ_USER};
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO ${DB_APP_READ_WRITE_USER};
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT, USAGE, UPDATE ON SEQUENCES TO ${DB_APP_READ_WRITE_USER};
SQL
