#!/bin/bash
set -e

# Ensure required env vars exist
: "${DB_APP_ADMIN_USER:?Missing DB_APP_ADMIN_USER}"
: "${DB_APP_NAME:?Missing DB_APP_NAME}"
: "${DB_MANAGEMENT_NAME:?Missing DB_MANAGEMENT_NAME}"
: "${DB_MANAGEMENT_ADMIN_USER:?Missing DB_MANAGEMENT_ADMIN_USER}"
: "${DB_MANAGEMENT_READ_USER:?Missing DB_MANAGEMENT_READ_USER}"
: "${DB_MANAGEMENT_READ_PASSWORD:?Missing DB_MANAGEMENT_READ_PASSWORD}"
: "${DB_MANAGEMENT_READ_WRITE_USER:?Missing DB_MANAGEMENT_READ_WRITE_USER}"
: "${DB_MANAGEMENT_READ_WRITE_PASSWORD:?Missing DB_MANAGEMENT_READ_WRITE_PASSWORD}"
: "${DB_MANAGEMENT_ADMIN_PASSWORD:?Missing DB_MANAGEMENT_ADMIN_PASSWORD}"

# 1. Connect as the app DB admin role to bootstrap the management DB
psql -v ON_ERROR_STOP=1 --username "$DB_APP_ADMIN_USER" --dbname "$DB_APP_NAME" <<SQL
DO \$\$
BEGIN
    IF NOT EXISTS (SELECT FROM pg_catalog.pg_roles WHERE rolname = '${DB_MANAGEMENT_ADMIN_USER}') THEN
        EXECUTE format('CREATE USER %I WITH CREATEDB CREATEROLE', '${DB_MANAGEMENT_ADMIN_USER}');
    END IF;
END
\$\$;
SQL

DB_EXISTS=$(psql -U "$DB_APP_ADMIN_USER" -d "$DB_APP_NAME" -tAc "SELECT 1 FROM pg_database WHERE datname='${DB_MANAGEMENT_NAME}'")
if [ "$DB_EXISTS" != "1" ]; then
  psql -U "$DB_APP_ADMIN_USER" -d "$DB_APP_NAME" -c "CREATE DATABASE ${DB_MANAGEMENT_NAME} OWNER ${DB_MANAGEMENT_ADMIN_USER};"
fi

# Set password for management DB admin role so create-superuser (and other TCP clients) can authenticate.
# DB passwords must not contain single quotes; automatic generators (setup.sh, create_management_db_secret.sh) emit hex-only.
psql -v ON_ERROR_STOP=1 --username "$DB_APP_ADMIN_USER" --dbname "$DB_APP_NAME" -c "ALTER USER \"${DB_MANAGEMENT_ADMIN_USER}\" WITH PASSWORD '${DB_MANAGEMENT_ADMIN_PASSWORD}';"

# 2. Connect to the new management DB as the management admin role to create access roles
psql -v ON_ERROR_STOP=1 --username "$DB_MANAGEMENT_ADMIN_USER" --dbname "$DB_MANAGEMENT_NAME" <<SQL
DO \$\$
BEGIN
    IF NOT EXISTS (SELECT FROM pg_catalog.pg_roles WHERE rolname = '${DB_MANAGEMENT_READ_USER}') THEN
        EXECUTE format('CREATE USER %I WITH PASSWORD %L', '${DB_MANAGEMENT_READ_USER}', '${DB_MANAGEMENT_READ_PASSWORD}');
    END IF;
END
\$\$;

DO \$\$
BEGIN
    IF NOT EXISTS (SELECT FROM pg_catalog.pg_roles WHERE rolname = '${DB_MANAGEMENT_READ_WRITE_USER}') THEN
        EXECUTE format('CREATE USER %I WITH PASSWORD %L', '${DB_MANAGEMENT_READ_WRITE_USER}', '${DB_MANAGEMENT_READ_WRITE_PASSWORD}');
    END IF;
END
\$\$;

-- Always sync passwords from env so DB stays aligned with secret values
DO \$\$
BEGIN
    EXECUTE format('ALTER USER %I WITH PASSWORD %L', '${DB_MANAGEMENT_READ_USER}', '${DB_MANAGEMENT_READ_PASSWORD}');
    EXECUTE format('ALTER USER %I WITH PASSWORD %L', '${DB_MANAGEMENT_READ_WRITE_USER}', '${DB_MANAGEMENT_READ_WRITE_PASSWORD}');
END
\$\$;

GRANT CONNECT ON DATABASE ${DB_MANAGEMENT_NAME} TO ${DB_MANAGEMENT_READ_USER}, ${DB_MANAGEMENT_READ_WRITE_USER};
GRANT USAGE ON SCHEMA public TO ${DB_MANAGEMENT_READ_USER}, ${DB_MANAGEMENT_READ_WRITE_USER};

GRANT SELECT ON ALL TABLES IN SCHEMA public TO ${DB_MANAGEMENT_READ_USER};
GRANT SELECT ON ALL SEQUENCES IN SCHEMA public TO ${DB_MANAGEMENT_READ_USER};

GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO ${DB_MANAGEMENT_READ_WRITE_USER};
GRANT SELECT, USAGE, UPDATE ON ALL SEQUENCES IN SCHEMA public TO ${DB_MANAGEMENT_READ_WRITE_USER};

ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT ON TABLES TO ${DB_MANAGEMENT_READ_USER};
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT ON SEQUENCES TO ${DB_MANAGEMENT_READ_USER};
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO ${DB_MANAGEMENT_READ_WRITE_USER};
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT, USAGE, UPDATE ON SEQUENCES TO ${DB_MANAGEMENT_READ_WRITE_USER};
SQL
