# Version: 5
# Filename: deployment.yaml
# Description: Valkey DB deployment. RedisInsight GUI is under infra/k8s/base/ops.
# UPDATE: Using configMapGenerator to mount entrypoint and healthcheck scripts.

apiVersion: apps/v1
kind: Deployment
metadata:
  name: podverse-keyvaldb
  labels:
    app: valkey
spec:
  replicas: 1
  selector:
    matchLabels:
      app: valkey
  template:
    metadata:
      labels:
        app: valkey
    spec:
      containers:
        - name: valkey
          # PLACEHOLDER: Kustomize will find this name and append the tag (e.g., :9.0.1)
          image: valkey/valkey
          command: ["/opt/keyvaldb/valkey-entrypoint.sh"]
          ports:
            - containerPort: 6379
          envFrom:
            - secretRef:
                name: podverse-keyvaldb-opaque
          volumeMounts:
            - name: data
              mountPath: /var/lib/valkey
            - name: scripts
              mountPath: /opt/keyvaldb
          securityContext:
            runAsUser: 999
            runAsGroup: 999
            runAsNonRoot: true
            allowPrivilegeEscalation: false
          livenessProbe:
            exec:
              command: ["/opt/keyvaldb/valkey-healthcheck.sh"]
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            exec:
              command: ["/opt/keyvaldb/valkey-healthcheck.sh"]
            initialDelaySeconds: 5
            periodSeconds: 10
      volumes:
        # EPHEMERAL STORAGE: Data is lost when pod restarts
        - name: data
          emptyDir: {}
        - name: scripts
          configMap:
            name: podverse-keyvaldb-scripts
            defaultMode: 0755
