# Version: 2
# Filename: kustomization.yaml
# Description: Bundles resources and manages image versions for Management API.

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - https://github.com/podverse/podverse//infra/k8s/base/management-api?ref=X.X.X-staging.N
  - https://github.com/podverse/podverse//infra/k8s/base/product-membership?ref=X.X.X-staging.N

namespace: podverse-alpha

labels:
  - pairs:
      app: podverse-management-api
      environment: alpha
    includeSelectors: true

configMapGenerator:
  - name: podverse-management-api-config
    behavior: merge
    envs:
      - source/management-api.env

patches:
  - path: deployment-link-patch.yaml

images:
  - name: ghcr.io/podverse/podverse/management-api
    newTag: "X.X.X-staging.N"
