# Version: 2
# Filename: kustomization.yaml
# Description: Bundles the Web frontend resources and centralizes the web image tag.

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - https://github.com/podverse/podverse//infra/k8d/base/web?ref=staging

namespace: podverse-alpha

labels:
  - pairs:
      app: podverse-web
      environment: alpha
    # This ensures the labels are also applied to the selectors,
    # so the Service correctly finds the Pods.
    includeSelectors: true

configMapGenerator:
  - name: podverse-web-runtime-config
    behavior: merge
    envs:
      - source/web-sidecar.env

images:
  - name: ghcr.io/podverse/podverse/web-deploy
    newTag: "5.4.12-staging.0"
  - name: ghcr.io/podverse/podverse/web-runtime-config
    newTag: "5.4.12-staging.0"

patches:
  - path: deployment-link-patch.yaml
  - path: node-configmap-patch.yaml
